### ISSUE TITLE
Remove display on specific pages?

### ISSUE THREAD

**Issue by rowild** [helgatheviking/KIA-Subtitle#10]
Is it possibile to subpress the display of the kia-subtitle field on specific pages, like on give ids ($page->id) or on specific page templates?

**Comment by helgatheviking** [comment]
You could remove the `add_input` method from it's hook under certain conditions. Or you could send me a PR with a filter in the `add_input()` method because currently the display is only controlled by the post type options.

**Comment by rowild** [comment]
Thanks for your response, but - no offense - for a good answer I would expect code samples... how is this going to help others? "under certain conditions" ... which ones e.g.???

**Comment by helgatheviking** [comment]
Apologies, but it wasn't meant to be a complete answer as this isn't a support forum. I'd send you to the wordpress.org forums where I handle support, but free support doesn't cover customizations as I advertise in both places.

>Support is handled in the WordPress forums. Please note that support is limited and does not cover any custom implementation of the plugin.

"Certain conditions" just means any conditional logic you can define: such as your suggestions for matching post IDs or matching the page template using [`get_page_template_slug()`](https://codex.wordpress.org/Function_Reference/get_page_template_slug). If your conditions are met, you could call [`remove_action()`](https://codex.wordpress.org/Function_Reference/remove_action).
