### ISSUE TITLE
Subtitle appears to be  not saving in Block Editor

### ISSUE THREAD

**Issue by dbreakers** [helgatheviking/KIA-Subtitle#18]
Subtitle was saving in classic editor and quick edit but failing on the new block editor and being deleted.

Seems like the code needs to be amended to check if $POST['subtitle'] exists before it being checked in meta_save

I added the line if(isset($_POST['subtitle'])) { which appears to correct the issue

	// Don't save if the subtitle equals the default text.
		if(isset($_POST['subtitle'])) {
		if( in_array ( trim($_POST['subtitle'] ), array( __( 'Subtitle', 'kia-subtitle' ), '' ) ) ) {
	      delete_post_meta( $post_id, 'kia_subtitle' );
		} else {
			update_post_meta( $post_id, 'kia_subtitle', sanitize_post_field( 'post_title', $_POST['subtitle'], $post_id, 'db' ) );
		}
		}

**Comment by dbreakers** [comment]
The issue appears to eb when you added the code to support for CPTs that don't support the new editor - this ends up with the nonce being added to page and included in the post.php payload.

**Comment by helgatheviking** [comment]
@dbreakers sorry to have missed this! Is this still happening? Can you confirm that it happens with no other plugins enabled and while using a default theme?

**Comment by dbreakers** [comment]
Thanks new release works and does something similar to the code I amended to my local copy work :-)
