### ISSUE TITLE
Backticks parsing formatting issue

### ISSUE THREAD

**Issue by codiceovvio** [helgatheviking/KIA-Subtitle#9]
Hi,
first of all thanks a lot for this useful plugin,
there is an issue maybe when WordPress parses the readme.txt file that breaks the FAQ layout,
both on plugin page in the plugins repository and when opening plugin info modal from the admin plugins list _as in this screenshot_:

![admin modal](https://cloud.githubusercontent.com/assets/10262157/16716513/bf7d4faa-46fe-11e6-962e-77c81110c6e1.png)

I am on Ubuntu 16.04 using firefox and chromium, if this may help
I also have this issue in translate.wordpress.org project, as you can see below

![translate wordpress](https://cloud.githubusercontent.com/assets/10262157/16716546/941ce676-46ff-11e6-8494-9d06e03651c6.png)

I suppose this may be for the same reason, the triple backticks syntax to delimit multiline code blocks.
As little as I can help, I made you a pull request with these small fixes, and wait before checking out these strings in translations.

thank you,

Marcello

**Comment by helgatheviking** [comment]
Glad you like it! and thanks for the PR. I'll try to get this uploaded to the .org repo soon.  Closed by 1487e9f7a1d5752b1518a60f71867aa2e1d8f3c9
